name: BanMan
version: 1.0
author: TheRandomGamer
main: me.therandomgamer.afkgames.me.therandomgamer.afkgames.Main
commands:
    afkgames:
      usage: /afkgames help
      description: The me.therandomgamer.afkgames.Main Command for the AFKGames Plugin